export const PRODUCT_CATEGORIES: string[] = [
  "Electronics",
  "Fashion & Apparel",
  "Home & Kitchen",
  "Beauty & Personal Care",
  "Health & Wellness",
  "Sports & Outdoors",
  "Toys & Games",
  "Books & Media",
  "Groceries & Food",
  "Pet Supplies",
  "Automotive",
  "Office & Stationery",
  "Baby & Kids",
  "Jewelry & Accessories",
  "Arts & Crafts",
  "Garden & Outdoor Living",
  "Furniture",
  "Tools & Home Improvement",
  "Musical Instruments",
  "Other",
];
